server:
  servlet:
    encoding:
      force-response: true

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: localhost
    username: root
    password: 1q2w3e4r
  application:
    name: hospital-review2

jwt:
  token:
    secret: hello
